import Config from 'react-native-config';

export const EndPoints = {
  signup: 'mobile/auth/signup',
  login: 'mobile/auth/login',
  updateUser: 'mobile/profile/update',
  getShiftsList: 'mobile/shifts/range',
  getShiftsFilter: 'mobile/shifts/filter',
  getFacilityUpComingShifts: 'mobile/shifts/facility/upcomingShifts',
  getFacilityOverview: 'mobile/shifts/facility/overview/',
  getIdenticalShifts: 'mobile/shifts/identical',
  getBlockedShifts: 'mobile/shifts/blocked',
  acceptIdenticalShift: 'mobile/shifts/identical/accept',
  acceptBlockedShift: 'mobile/shifts/blocked/accept',
  getShiftDetails: 'mobile/shifts/details',
  getUserNotificationSettings: 'mobile/profile/settings/',
  updateUserNotificationSettings: 'mobile/profile/settings/update',
  getUserProfileDetails: 'mobile/profile/',
  updateUserBio: 'mobile/profile/update/bio/',
  updateUserAvatar: 'mobile/profile/update/avatar/',
  getStafferProfileDocuments: 'mobile/profile/documents/',
  stafferProfileDocumentsSubmit: 'mobile/profile/document/submit',
  deleteStafferProfileDocument: 'mobile/profile/document/delete/',
  updateStafferProfileDocument: 'mobile/profile/document/update/',
  stafferProfileBonusDocumentSubmit: 'mobile/profile/document/bonus/submit',
  deleteStafferProfileBonusDocument: 'mobile/profile/document/bonus/delete/',
  changeProfileCompleteStatus: 'mobile/profile/changeProfileCompleteStatus',
  getScheduleShifts: 'mobile/schedule/shifts/',
  getShiftTimeLine: 'mobile/schedule/getShiftTimelineData',
  shiftClockIn: 'mobile/schedule/ShiftClockedIn',
  shiftClockOut: 'mobile/schedule/ShiftClockedOut',
  shiftTakeBreak: 'mobile/schedule/ShiftTakeBreak',
  shiftResume: 'mobile/schedule/ShiftResume',
  shiftRating: 'mobile/schedule/ShiftRating',
  shiftCalledOff: 'mobile/schedule/ShiftCalledOff',
  getStatsTiles: 'mobile/stats/tiles',
  getEarningHours: 'mobile/stats/earningHours/',
  getGraph: 'mobile/stats/graph/',
  notifications: 'dashboard/notification',
  getMessages: 'mobile/alerts/chat/messages',
  sendMessages: 'mobile/alerts/send/message',
  getUnReadMessages: 'mobile/alerts/chat/messages/unread',
  reportChat: 'mobile/alerts/chat/report',
  resetPassword: 'mobile/auth/resetPassword',
  geoCode: 'maps/api/geocode/json',
  messageGigworx: 'mobile/alerts/chat/initiate',
  getAppVersion: 'mobile/platform/',
  forgotPasswordOtp: 'dashboard/auth/forgotPasswordOtp',
  checkEmail: 'mobile/auth/account/status',
  deleteProfile: 'mobile/profile/delete/',
  locationOffset: 'maps/api/timezone/json',
};

export const BaseUrl = {
  baseUrl: 'https://api-sandbox.bl326.bluelabellabs.io/api/v1/',
};

export const GeoCodeBaseUrl = {
  baseUrl: 'https://maps.googleapis.com/',
};
